config/routes.rb
Rails.application.routes.draw do
  root :to => "tasks#index"


  resources :categories 
  resources :tasks
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    validates :category_name, presence: true, uniqueness: true
    validates :category_details, presence: true

    has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  validates :task_name, presence: true, uniqueness: true
  validates :task_details, presence: true
  
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def index
        @categories = Category.all
    end
 
    def new
         @category = Category.new
    end
 
    def create
         @category = Category.new(category_params)
 
        if @category.valid? 
             @category.save
             redirect_to @category
        else
             render :new
        end 
    end
 
    def show
         @category = Category.find(params[:id])
    end
 
    def edit
         @category = Category.find(params[:id])
    end
 
    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
             flash[:notice] = "The category has been updated successfully"
             redirect_to @category
        else
             flash[:notice] = "Meh, something went wrong."
             render :edit
        end
    end
 
    def destroy
         @category = Category.find(params[:id])
         @category.destroy
         flash[:notice] = "Category has been deleted."
         redirect_to categories_path 
    end
 
    private 
 
    def category_params
         params.require(:category).permit(:category_name, :category_details)
    end
 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :fetch_category
  
  def index
    @categories = Category.all

    category_1 = params[:category_1]

    if !category_1.nil?
      @tasks = Task.where(:category_id => category_1)
    else
      @tasks = Task.all
    end
  end
  
  def show
    @task = Task.find(params[:id])
  end
  
  def new
    @task = Task.new
  end
  
  def create
    @task = Task.create(task_params)

    if @task.valid?
      @task.save
      redirect_to @task
    else
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to @task
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])

    @task.destroy
    redirect_to :action => :index
  end
  
  private
  def task_params
    params.require(:task).permit(:task_name,:task_details, :category_id)
  end

  def fetch_category
    @category = Category.find(params[:category_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_form.html.erb
  <%= form_with(model: category, local: true) do |form| %>
  <div class="field">
    <%= form.label :category_name %>
    <%= form.text_field :category_name %>
  </div>
  <div class="field">
    <%= form.label :category_details %>
    <%= form.text_area :category_details %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= form_for @category do |f| %>

<%= f.label :category_name %>
<%= f.text_field :category_name %>
<%= f.label :category_details %>
<%= f.text_area :category_details %>

<%= f.submit %>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render "form", category: @category %>

<%= link_to 'View', category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.category_name %></td>
        <td><%= link_to 'View', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>Create New Category</h1>

<%= render "form", category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<h1>View Category</h1>

<h3><%= @category.category_name %></h3>

<p><%= @category.category_details %></p>

<%= link_to 'Edit', edit_category_path(@category.id) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoListApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Jaren's Todo App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-md-auto">
      <li class="nav-item active">
<%= link_to "Create Task", new_task_path, class: 'nav-link' %>

      </li>
      
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/layouts/staticpage.html.erb
<!-- Section 1 -->
<section class="bg-white">
    <div class="w-full px-5 py-6 mx-auto space-y-5 sm:py-8 md:py-12 sm:space-y-8 md:space-y-16 max-w-7xl">

        <div class="flex flex-col items-center sm:px-5 md:flex-row">
            <div class="w-full md:w-1/2">
                <a href="#_" class="block">
                    <img class="object-cover w-full h-full rounded-lg max-h-64 sm:max-h-96" src="https://cdn.devdojo.com/images/may2021/cupcakes.jpg">
                </a>
            </div>
            <div class="flex flex-col items-start justify-center w-full h-full py-6 mb-6 md:mb-0 md:w-1/2">
                <div class="flex flex-col items-start justify-center h-full space-y-3 transform md:pl-10 lg:pl-16 md:space-y-5">
                    <div class="bg-pink-500 flex items-center pl-2 pr-3 py-1.5 leading-none rounded-full text-xs font-medium uppercase text-white inline-block">
                        <svg class="w-3.5 h-3.5 mr-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path></svg>
                        <span>Featured</span>
                    </div>
                    <h1 class="text-4xl font-bold leading-none lg:text-5xl xl:text-6xl"><a href="#_">Savory Templates. Sweet Designs.</a></h1>
                    <p class="pt-2 text-sm font-medium">by <a href="#_" class="mr-1 underline">John Doe</a> · <span class="mx-1">April 23rd, 2021</span> · <span class="mx-1 text-gray-600">5 min. read</span></p>
                </div>
            </div>
        </div>

        <div class="flex grid grid-cols-12 pb-10 sm:px-5 gap-x-8 gap-y-16">
            <div class="flex flex-col items-start col-span-12 space-y-3 sm:col-span-6 xl:col-span-4">
                <a href="#_" class="block">
                    <img class="object-cover w-full mb-2 overflow-hidden rounded-lg shadow-sm max-h-56" src="https://cdn.devdojo.com/images/may2021/fruit.jpg">
                </a>
                <div class="bg-purple-500 flex items-center px-3 py-1.5 leading-none rounded-full text-xs font-medium uppercase text-white inline-block">
                    <span>Lifestyle</span>
                </div>
                <h2 class="text-lg font-bold sm:text-xl md:text-2xl"><a href="#_">Creating a Future Worth Living</a></h2>
                <p class="text-sm text-gray-500">Learn the attributes you need to gain in order to build a future and create a life that you are truly happy with.</p>
                <p class="pt-2 text-xs font-medium"><a href="#_" class="mr-1 underline">Mary Jane</a> · <span class="mx-1">April 17, 2021</span> · <span class="mx-1 text-gray-600">3 min. read</span></p>
            </div>

            <div class="flex flex-col items-start col-span-12 space-y-3 sm:col-span-6 xl:col-span-4">
                <a href="#_" class="block">
                    <img class="object-cover w-full mb-2 overflow-hidden rounded-lg shadow-sm max-h-56" src="https://cdn.devdojo.com/images/may2021/workout.jpg">
                </a>
                <div class="bg-pink-500 flex items-center px-3 py-1.5 leading-none rounded-full text-xs font-medium uppercase text-white inline-block">
                    <span>Health</span>
                </div>
                <h2 class="text-lg font-bold sm:text-xl md:text-2xl">The Healther Version of Yourself</h2>
                <p class="text-sm text-gray-500">If you want to excel in life and become a better version of yourself, you'll need to upgrade your life.</p>
                <p class="pt-2 text-xs font-medium"><a href="#_" class="mr-1 underline">Fred Jones</a> · <span class="mx-1">April 10, 2021</span> · <span class="mx-1 text-gray-600">3 min. read</span></p>
            </div>

            <div class="flex flex-col items-start col-span-12 space-y-3 sm:col-span-6 xl:col-span-4">
                <a href="#_" class="block">
                    <img class="object-cover w-full mb-2 overflow-hidden rounded-lg shadow-sm max-h-56" src="https://cdn.devdojo.com/images/may2021/food.jpg">
                </a>
                <div class="bg-red-500 flex items-center px-3 py-1.5 leading-none rounded-full text-xs font-medium uppercase text-white inline-block">
                    <span>Food</span>
                </div>
                <h2 class="text-lg font-bold sm:text-xl md:text-2xl">Enjoy the Meals of the Kings</h2>
                <p class="text-sm text-gray-500">Take the time to enjoy the life that you've created. It's totally fine to live like kings and eat like royalty.</p>
                <p class="pt-2 text-xs font-medium"><a href="#_" class="mr-1 underline">Mike Roberts</a> · <span class="mx-1">April 6, 2021</span> · <span class="mx-1 text-gray-600">3 min. read</span></p>
            </div>

            <div class="flex flex-col items-start col-span-12 space-y-3 sm:col-span-6 xl:col-span-4">
                <a href="#_" class="block">
                    <img class="object-cover w-full mb-2 overflow-hidden rounded-lg max-h-56" src="https://cdn.devdojo.com/images/may2021/books.jpg">
                </a>
                <div class="bg-blue-500 flex items-center px-3 py-1.5 leading-none rounded-full text-xs font-medium uppercase text-white inline-block">
                    <span>Motivation</span>
                </div>
                <h2 class="text-lg font-bold sm:text-xl md:text-2xl">Writing for Success</h2>
                <p class="text-sm text-gray-500">Writing about your plans for success is extremely helpful for yourself and it will allow you to share your story.</p>
                <p class="pt-2 text-xs font-medium"><a href="#_" class="mr-1 underline">Tom Johnson</a> · <span class="mx-1">May 25, 2021</span> · <span class="mx-1 text-gray-600">3 min. read</span></p>
            </div>

            <div class="flex flex-col items-start col-span-12 space-y-3 sm:col-span-6 xl:col-span-4">
                <a href="#_" class="block">
                    <img class="object-cover w-full mb-2 overflow-hidden rounded-lg max-h-56" src="https://cdn.devdojo.com/images/may2021/clock.jpg">
                </a>
                <div class="bg-gray-800 flex items-center px-3 py-1.5 leading-none rounded-full text-xs font-medium uppercase text-white inline-block">
                    <span>Business</span>
                </div>
                <h2 class="text-lg font-bold sm:text-xl md:text-2xl">Simple Time Management</h2>
                <p class="text-sm text-gray-500">Managing your time can make the difference between getting ahead in life or staying exactly where you are.</p>
                <p class="pt-2 text-xs font-medium"><a href="#_" class="mr-1 underline">Scott Reedman</a> · <span class="mx-1">May 18, 2021</span> · <span class="mx-1 text-gray-600">3 min. read</span></p>
            </div>

            <div class="flex flex-col items-start col-span-12 space-y-3 sm:col-span-6 xl:col-span-4">
                <a href="#_" class="block">
                    <img class="object-cover w-full mb-2 overflow-hidden rounded-lg max-h-56" src="https://cdn.devdojo.com/images/may2021/lemons.jpg">
                </a>
                <div class="bg-yellow-400 flex items-center px-3 py-1.5 leading-none rounded-full text-xs font-medium uppercase text-white inline-block">
                    <span>Nutrition</span>
                </div>
                <h2 class="text-lg font-bold sm:text-xl md:text-2xl">The Fruits Life</h2>
                <p class="text-sm text-gray-500">Take a moment and enjoy to enjoy the many fruits of life. Relaxation and a healthy diet can go a long way.</p>
                <p class="pt-2 text-xs font-medium"><a href="#_" class="mr-1 underline">Jake Caldwell</a> · <span class="mx-1">May 15, 2021</span> · <span class="mx-1 text-gray-600">3 min. read</span></p>
            </div>

        </div>
    </div>
</section>

app/views/tasks/_form.html.erb
<div class="flex-row d-flex justify-task_details-center">

<div class="col-md-8">
<div class="card mt-5">

    <div class="card-body">
    <%= form_for @task do |f| %>
    
    <div class="form-group">
    <%= f.label :task_name%>
    <%= f.text_field :task_name, class: 'form-control' %>
    
    </div>

    <div class="form-group">

    
    <%= f.label :task_details%>
    <%= f.text_area :task_details, class: 'form-control'%>

    </div>

    <div class="form-group">

    <%= f.select :category_id, Category.all.map {|c| [c.category_name, c.id]} %>

    </div>

    <%= f.submit "Create Task", class: 'btn btn-primary' %>
    <%= link_to "Back", tasks_path, class: 'btn btn-secondary' %>
<% end %>

    </div>
</div>


</div>

</div>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= render "form" %>

app/views/tasks/index.html.erb
<div class="container">
    <div class="row">
    <div class="col-md-8">
    <div class="row">
   
     <% @tasks.each do |task| %>
        <div class="col-md-6">
            <div class="card mt-3">
                <div class="card-body">
                    <h3><%= link_to task.task_name, task_path(task.id) %></h3>
                    <%= link_to "View", task_path(task.id), class: 'btn btn-primary'%>
                </div>
            </div>
        </div>
          <% end %>
      </div>
    </div>

    <div class="col-md-4">

    <div class="card mt-3">
        <div class="card-header">
            Categories
        </div>

        <div class="card-body">

        <ul class="list-group">

         <% @categories.each do |category| %>

        
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <%= link_to category.category_name, tasks_path(:category_1 => category.id) %>
    <span class="badge badge-primary badge-pill"><%= category.tasks.count %></span>
  </li>
       <% end %>
        </ul>
        </div>
    </div>
    </div>   
 </div>
    </div>
</div>

app/views/tasks/new.html.erb
<h1>Create New Task</h1>

<%= render 'form' %>

app/views/tasks/show.html.erb
<h1>Show Task</h1>
<div class="container-fluid mt-3">
<h1>Category: <%= @task.category.category_name %></h1>
<h3><%= @task.task_name %></h3>


<p><%= @task.task_details %></p>


<%= link_to "Edit", edit_task_path(@task.id), class: 'btn btn-primary' %>
<%= link_to "Delete", task_path(@task.id), method: :delete, class: 'btn btn-danger' %>
<%= link_to "Back", tasks_path, class: 'btn btn-secondary'%>
</div>